apiVersion: v1
kind: Service
metadata:
  name: riskapp-api
  namespace: riskapp
spec:
  type: ClusterIP
  selector:
    app: riskapp-api
  ports:
    - port: 8000
      name: http
      targetPort: http