"""baseline server schema

Revision ID: 0001
Revises:
Create Date: 2026-08-11 05:11:39.219894

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_superuser", sa.Boolean(), nullable=False),
        sa.Column("deactivated_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_users_email"), ["email"], unique=True)

    op.create_table(
        "password_reset_tokens",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.String(length=128), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("used_at", sa.DateTime(), nullable=True),
        sa.Column("request_ip", sa.String(length=64), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash", name="uq_password_reset_token_hash"),
    )
    with op.batch_alter_table("password_reset_tokens", schema=None) as batch_op:
        batch_op.create_index("ix_password_reset_expires", ["expires_at"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_password_reset_tokens_user_id"), ["user_id"], unique=False
        )
        batch_op.create_index(
            "ix_password_reset_user_active", ["user_id", "used_at"], unique=False
        )

    op.create_table(
        "projects",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("projects", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_projects_name"), ["name"], unique=False)

    op.create_table(
        "refresh_tokens",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.String(length=128), nullable=False),
        sa.Column("issued_at", sa.DateTime(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("revoked_at", sa.DateTime(), nullable=True),
        sa.Column("replaced_by_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash", name="uq_refresh_token_hash"),
    )
    with op.batch_alter_table("refresh_tokens", schema=None) as batch_op:
        batch_op.create_index("ix_refresh_tokens_expires", ["expires_at"], unique=False)
        batch_op.create_index(
            "ix_refresh_tokens_user_active", ["user_id", "revoked_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_refresh_tokens_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "audit_log",
        sa.Column("ts", sa.DateTime(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("change_id", sa.Uuid(), nullable=False),
        sa.Column("entity", sa.String(length=40), nullable=False),
        sa.Column("entity_id", sa.Uuid(), nullable=False),
        sa.Column("op", sa.String(length=20), nullable=False),
        sa.Column("before", sa.JSON(), nullable=True),
        sa.Column("after", sa.JSON(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("audit_log", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_audit_log_change_id"), ["change_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_audit_log_entity"), ["entity"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_audit_log_entity_id"), ["entity_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_audit_log_project_id"), ["project_id"], unique=False
        )
        batch_op.create_index(
            "ix_audit_log_project_ts", ["project_id", "ts"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_audit_log_ts"), ["ts"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_audit_log_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "helpdesk_tickets",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("category", sa.String(length=40), nullable=False),
        sa.Column("priority", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("reporter_email", sa.String(length=320), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.CheckConstraint(
            "category IN ('bug','question','feature_request','access','other')",
            name="ck_helpdesk_category",
        ),
        sa.CheckConstraint(
            "priority IN ('low','medium','high','critical')",
            name="ck_helpdesk_priority",
        ),
        sa.CheckConstraint(
            "status IN ('open','in_progress','resolved','closed')",
            name="ck_helpdesk_status",
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("helpdesk_tickets", schema=None) as batch_op:
        batch_op.create_index(
            "ix_helpdesk_project_deleted_updated",
            ["project_id", "is_deleted", "updated_at"],
            unique=False,
        )
        batch_op.create_index(
            "ix_helpdesk_project_priority", ["project_id", "priority"], unique=False
        )
        batch_op.create_index(
            "ix_helpdesk_project_status_created",
            ["project_id", "status", "created_at"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_helpdesk_tickets_category"), ["category"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_helpdesk_tickets_created_by"), ["created_by"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_helpdesk_tickets_is_deleted"), ["is_deleted"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_helpdesk_tickets_priority"), ["priority"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_helpdesk_tickets_project_id"), ["project_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_helpdesk_tickets_status"), ["status"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_helpdesk_tickets_updated_at"), ["updated_at"], unique=False
        )

    op.create_table(
        "items",
        sa.Column("type", sa.String(length=20), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("probability", sa.Integer(), nullable=False),
        sa.Column("impact", sa.Integer(), nullable=False),
        sa.Column("impact_cost", sa.Integer(), nullable=True),
        sa.Column("impact_time", sa.Integer(), nullable=True),
        sa.Column("impact_scope", sa.Integer(), nullable=True),
        sa.Column("impact_quality", sa.Integer(), nullable=True),
        sa.Column("code", sa.String(length=60), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("category", sa.String(length=120), nullable=True),
        sa.Column("threat", sa.Text(), nullable=True),
        sa.Column("triggers", sa.Text(), nullable=True),
        sa.Column("mitigation_plan", sa.Text(), nullable=True),
        sa.Column("document_url", sa.Text(), nullable=True),
        sa.Column("owner_user_id", sa.Uuid(), nullable=True),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("identified_at", sa.DateTime(), nullable=False),
        sa.Column("status_changed_at", sa.DateTime(), nullable=False),
        sa.Column("response_at", sa.DateTime(), nullable=True),
        sa.Column("occurred_at", sa.DateTime(), nullable=True),
        sa.Column("score", sa.Integer(), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.CheckConstraint("impact BETWEEN 1 AND 5", name="ck_items_impact_1_5"),
        sa.CheckConstraint(
            "probability BETWEEN 1 AND 5", name="ck_items_probability_1_5"
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["owner_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_id", "code", name="uq_items_project_code"),
    )
    with op.batch_alter_table("items", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_items_category"), ["category"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_items_code"), ["code"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_items_identified_at"), ["identified_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_items_is_deleted"), ["is_deleted"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_items_owner_user_id"), ["owner_user_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_items_project_id"), ["project_id"], unique=False
        )
        batch_op.create_index(
            "ix_items_project_type_deleted_score",
            ["project_id", "type", "is_deleted", "score"],
            unique=False,
        )
        batch_op.create_index(
            "ix_items_project_type_updated",
            ["project_id", "type", "updated_at"],
            unique=False,
        )
        batch_op.create_index(batch_op.f("ix_items_score"), ["score"], unique=False)
        batch_op.create_index(batch_op.f("ix_items_status"), ["status"], unique=False)
        batch_op.create_index(batch_op.f("ix_items_type"), ["type"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_items_updated_at"), ["updated_at"], unique=False
        )

    op.create_table(
        "project_members",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_id", "user_id", name="uq_project_user"),
    )
    with op.batch_alter_table("project_members", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_project_members_project_id"), ["project_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_project_members_role"), ["role"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_project_members_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "score_snapshots",
        sa.Column("batch_id", sa.Uuid(), nullable=False),
        sa.Column("captured_at", sa.DateTime(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("item_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("probability", sa.Integer(), nullable=False),
        sa.Column("impact", sa.Integer(), nullable=False),
        sa.Column("score", sa.Integer(), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("score_snapshots", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_score_snapshots_batch_id"), ["batch_id"], unique=False
        )
        batch_op.create_index(
            "ix_score_snapshots_batch_score", ["batch_id", "score"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_score_snapshots_captured_at"), ["captured_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_score_snapshots_created_by"), ["created_by"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_score_snapshots_item_id"), ["item_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_score_snapshots_kind"), ["kind"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_score_snapshots_project_id"), ["project_id"], unique=False
        )
        batch_op.create_index(
            "ix_score_snapshots_project_kind_captured",
            ["project_id", "kind", "captured_at"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_score_snapshots_score"), ["score"], unique=False
        )

    op.create_table(
        "sync_receipts",
        sa.Column("change_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("entity", sa.String(length=40), nullable=False),
        sa.Column("entity_id", sa.Uuid(), nullable=True),
        sa.Column("op", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("response", sa.JSON(), nullable=False),
        sa.Column("processed_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("change_id"),
        sa.UniqueConstraint(
            "change_id", "user_id", "project_id", name="uq_sync_receipt"
        ),
    )
    with op.batch_alter_table("sync_receipts", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_sync_receipts_entity"), ["entity"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_sync_receipts_entity_id"), ["entity_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_sync_receipts_project_id"), ["project_id"], unique=False
        )
        batch_op.create_index(
            "ix_sync_receipts_project_processed",
            ["project_id", "processed_at"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_sync_receipts_status"), ["status"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_sync_receipts_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "actions",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("item_id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("owner_user_id", sa.Uuid(), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(["item_id"], ["items.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["owner_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("actions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_actions_created_by"), ["created_by"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_actions_is_deleted"), ["is_deleted"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_actions_item_id"), ["item_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_actions_kind"), ["kind"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_actions_owner_user_id"), ["owner_user_id"], unique=False
        )
        batch_op.create_index(
            "ix_actions_project_deleted_updated",
            ["project_id", "is_deleted", "updated_at"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_actions_project_id"), ["project_id"], unique=False
        )
        batch_op.create_index(
            "ix_actions_project_item", ["project_id", "item_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_actions_status"), ["status"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_actions_updated_at"), ["updated_at"], unique=False
        )

    op.create_table(
        "assessments",
        sa.Column("item_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("assessor_user_id", sa.Uuid(), nullable=False),
        sa.Column("probability", sa.Integer(), nullable=False),
        sa.Column("impact", sa.Integer(), nullable=False),
        sa.Column("score", sa.Integer(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["assessor_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(["item_id"], ["items.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("item_id", "assessor_user_id", name="uq_item_assessor"),
    )
    with op.batch_alter_table("assessments", schema=None) as batch_op:
        batch_op.create_index(
            "ix_assessments_assessor_updated",
            ["assessor_user_id", "updated_at"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_assessments_assessor_user_id"),
            ["assessor_user_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_assessments_is_deleted"), ["is_deleted"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_assessments_item_id"), ["item_id"], unique=False
        )
        batch_op.create_index(
            "ix_assessments_item_updated", ["item_id", "updated_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_assessments_score"), ["score"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_assessments_updated_at"), ["updated_at"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("assessments", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_assessments_updated_at"))
        batch_op.drop_index(batch_op.f("ix_assessments_score"))
        batch_op.drop_index("ix_assessments_item_updated")
        batch_op.drop_index(batch_op.f("ix_assessments_item_id"))
        batch_op.drop_index(batch_op.f("ix_assessments_is_deleted"))
        batch_op.drop_index(batch_op.f("ix_assessments_assessor_user_id"))
        batch_op.drop_index("ix_assessments_assessor_updated")

    op.drop_table("assessments")
    with op.batch_alter_table("actions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_actions_updated_at"))
        batch_op.drop_index(batch_op.f("ix_actions_status"))
        batch_op.drop_index("ix_actions_project_item")
        batch_op.drop_index(batch_op.f("ix_actions_project_id"))
        batch_op.drop_index("ix_actions_project_deleted_updated")
        batch_op.drop_index(batch_op.f("ix_actions_owner_user_id"))
        batch_op.drop_index(batch_op.f("ix_actions_kind"))
        batch_op.drop_index(batch_op.f("ix_actions_item_id"))
        batch_op.drop_index(batch_op.f("ix_actions_is_deleted"))
        batch_op.drop_index(batch_op.f("ix_actions_created_by"))

    op.drop_table("actions")
    with op.batch_alter_table("sync_receipts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_sync_receipts_user_id"))
        batch_op.drop_index(batch_op.f("ix_sync_receipts_status"))
        batch_op.drop_index("ix_sync_receipts_project_processed")
        batch_op.drop_index(batch_op.f("ix_sync_receipts_project_id"))
        batch_op.drop_index(batch_op.f("ix_sync_receipts_entity_id"))
        batch_op.drop_index(batch_op.f("ix_sync_receipts_entity"))

    op.drop_table("sync_receipts")
    with op.batch_alter_table("score_snapshots", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_score_snapshots_score"))
        batch_op.drop_index("ix_score_snapshots_project_kind_captured")
        batch_op.drop_index(batch_op.f("ix_score_snapshots_project_id"))
        batch_op.drop_index(batch_op.f("ix_score_snapshots_kind"))
        batch_op.drop_index(batch_op.f("ix_score_snapshots_item_id"))
        batch_op.drop_index(batch_op.f("ix_score_snapshots_created_by"))
        batch_op.drop_index(batch_op.f("ix_score_snapshots_captured_at"))
        batch_op.drop_index("ix_score_snapshots_batch_score")
        batch_op.drop_index(batch_op.f("ix_score_snapshots_batch_id"))

    op.drop_table("score_snapshots")
    with op.batch_alter_table("project_members", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_project_members_user_id"))
        batch_op.drop_index(batch_op.f("ix_project_members_role"))
        batch_op.drop_index(batch_op.f("ix_project_members_project_id"))

    op.drop_table("project_members")
    with op.batch_alter_table("items", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_items_updated_at"))
        batch_op.drop_index(batch_op.f("ix_items_type"))
        batch_op.drop_index(batch_op.f("ix_items_status"))
        batch_op.drop_index(batch_op.f("ix_items_score"))
        batch_op.drop_index("ix_items_project_type_updated")
        batch_op.drop_index("ix_items_project_type_deleted_score")
        batch_op.drop_index(batch_op.f("ix_items_project_id"))
        batch_op.drop_index(batch_op.f("ix_items_owner_user_id"))
        batch_op.drop_index(batch_op.f("ix_items_is_deleted"))
        batch_op.drop_index(batch_op.f("ix_items_identified_at"))
        batch_op.drop_index(batch_op.f("ix_items_code"))
        batch_op.drop_index(batch_op.f("ix_items_category"))

    op.drop_table("items")
    with op.batch_alter_table("helpdesk_tickets", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_helpdesk_tickets_updated_at"))
        batch_op.drop_index(batch_op.f("ix_helpdesk_tickets_status"))
        batch_op.drop_index(batch_op.f("ix_helpdesk_tickets_project_id"))
        batch_op.drop_index(batch_op.f("ix_helpdesk_tickets_priority"))
        batch_op.drop_index(batch_op.f("ix_helpdesk_tickets_is_deleted"))
        batch_op.drop_index(batch_op.f("ix_helpdesk_tickets_created_by"))
        batch_op.drop_index(batch_op.f("ix_helpdesk_tickets_category"))
        batch_op.drop_index("ix_helpdesk_project_status_created")
        batch_op.drop_index("ix_helpdesk_project_priority")
        batch_op.drop_index("ix_helpdesk_project_deleted_updated")

    op.drop_table("helpdesk_tickets")
    with op.batch_alter_table("audit_log", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_audit_log_user_id"))
        batch_op.drop_index(batch_op.f("ix_audit_log_ts"))
        batch_op.drop_index("ix_audit_log_project_ts")
        batch_op.drop_index(batch_op.f("ix_audit_log_project_id"))
        batch_op.drop_index(batch_op.f("ix_audit_log_entity_id"))
        batch_op.drop_index(batch_op.f("ix_audit_log_entity"))
        batch_op.drop_index(batch_op.f("ix_audit_log_change_id"))

    op.drop_table("audit_log")
    with op.batch_alter_table("refresh_tokens", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_refresh_tokens_user_id"))
        batch_op.drop_index("ix_refresh_tokens_user_active")
        batch_op.drop_index("ix_refresh_tokens_expires")

    op.drop_table("refresh_tokens")
    with op.batch_alter_table("projects", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_projects_name"))

    op.drop_table("projects")
    with op.batch_alter_table("password_reset_tokens", schema=None) as batch_op:
        batch_op.drop_index("ix_password_reset_user_active")
        batch_op.drop_index(batch_op.f("ix_password_reset_tokens_user_id"))
        batch_op.drop_index("ix_password_reset_expires")

    op.drop_table("password_reset_tokens")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_email"))

    op.drop_table("users")
    # ### end Alembic commands ###
